#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -x

ensemble-log "install script"

export TERM=linux

# Add the Hadoop PPA
ensemble-log "Adding ppa"
apt-add-repository ppa:canonical-sig/thirdparty
ensemble-log "updating cache"
apt-get update

# Install the packages
ensemble-log "installing packages"
DEBIAN_FRONTEND=noninteractive apt-get install -y hadoop-0.20-datanode hadoop-0.20-tasktracker

